config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:show, :index]

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
	has_many :technologies, inverse_of: :portfolio, dependent: :destroy
	accepts_nested_attributes_for :technologies, 
								   reject_if: lambda { |attrs| attrs['name'].blank?}
			


  	validates_presence_of :title, :body

    mount_uploader :thumb_image, PortfolioUploader
     mount_uploader :main_image, PortfolioUploader

  	def self.angular
  		where(subtitle: "Angular")
  	end

    def self.by_position
      order("position ASC")
      
    end
   
  	
end


  

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
	before_action :set_portfolio, only: [:show, :edit, :update, :destroy]
	  access all: [:show, :index, :angular, :ruby_on_rails], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all

	layout 'portfolio'

	def index
		@portfolio_items = Portfolio.by_position
	end

	 def sort
	    params[:order].each do |key, value|
	      Portfolio.find(value[:id]).update(position: value[:position])
	    end
	    
	end




	def angular
		@angular_portfolio_items = Portfolio.angular
	end
	def ruby_on_rails
		@rails_portfolio_items = Portfolio.ruby_on_rails_portfolio_items
	end
	def new 
		@portfolio_item = Portfolio.new

	end
	def create 
		@portfolio_item = Portfolio.new(portfolio_params)
		respond_to do |format|
			if @portfolio_item.save
				format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully created.' }
			else
				format.html {render new}
			end
		end
	end
	def show

	end
	def edit
	end
	def destroy
		
		@portfolio_item.destroy
		 respond_to do |format|
		    format.html { redirect_to portfolios_path, notice: 'Record was remove.' }
		 end

	end
	def update
		respond_to do |format|
	      if @portfolio_item.update(portfolio_params)
	        format.html { redirect_to portfolios_path, notice: 'Record was successfully updated.' }
	      else 
	        format.html { render :edit }
	      end
    	end
	end
	private 
		def portfolio_params 
			params.require(:portfolio).permit(:title, 
											  :subtitle, 
											  :body,
											  :main_image,
											  :thumb_image,
											   technologies_attributes: [:id, :name, :_destroy]
											   )
		end
		def set_portfolio 
			@portfolio_item = Portfolio.find(params[:id])
		end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
	def image_generator(height:, width: )
		"http://via.placeholder.com/#{height}x#{width}" 
	end
	def portfolio_img img, type
		if img.model.main_image? || img.model.thumb_image?
			img
		elsif type== :thumb
			image_generator(height: '350', width: '200' )
		else
			image_generator(height: '350', width: '200' )
		end

	end
 end 

app/views/portfolios/_form.html.erb
 <%= form_with(model: portfolio , local: true) do |f| %>

  <%portfolio.errors.full_messages.each do |error|%>
     <%=alert_generation(error)%>
  <%end%>
  <div class="row">
    <div class ="col-md-6">

      <div class="form-group">
        <%= f.text_field :title, class: "form-control", placeholder: "Title"%>
      </div>
       <div class="form-group">
          <%= f.label :subtitle %>
          <%= f.text_field :subtitle, class: "form-control", placeholder: "Subtitle" %>
        </div>
        <div class="form-group">
          <label class="btn btn-primary">
            Upload thumb image file<%= f.file_field :thumb_image, style: 'display: none'  %>

         
        </div>
        <div class="form-group">
          <label class="btn btn-primary">
            Upload main image file<%= f.file_field :main_image, style: 'display: none'  %>
          </label>
          
        </div>

    
    </div>

    <div class ="col-md-6"> 
      
       <div class="form-group">
          <%= f.label :body %>
          <%= f.text_area :body, class: "form-control", row:  13, placeholder: "Body" %>
        </div>
    </div>

  </div>
  
  <h2>Technologies Used</h2>
  <%=f.fields_for :technologies do |t| %>
  <div class="form-group">
    <%= render 'technology_fields', :f => t %>  
  </div>
  <%end%>
    <div class='links'>
      <%= link_to_add_association f, :technologies do%>

        <i class="fa fa-plus-square">Add tecnology</i> 
        
      <%end%>

    </div>

 
    
  <div class="form-group">
     <%= f.submit "Save Portfolio Item", class: "btn btn-primary btn-block"  %>
  </div>
 
<% end %> 

app/views/portfolios/_portfolio_item.html.erb
 

<div class="col-md-4 col-sm-12 " >
	<div class="card mb-4 box-shadow" data-id="<%= portfolio_item.id %>">
		
		<%= image_tag portfolio_img(portfolio_item.thumb_image, 'thumb'),  class: "card-img-top",  height: '200', width: '350'%>

		<div class="card-body">
			<p class="card-text">

				<span><%=link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></span> 
					

			</p>
			<div class="d-flex justify-content-between align-items-center">


			<div class="btn-group">
				<%=link_to "Edit", edit_portfolio_path(portfolio_item), class: "btn btn-sm btn-outline-secondary" if logged_in?(:site_admin)%>
				<%=link_to "delete", portfolio_path(portfolio_item), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-sm btn-outline-secondary" if logged_in?(:site_admin)%>
			</div>


			<small class="text-muted"><%=distance_of_time_in_words(portfolio_item.created_at, Time.now)%></small>
			</div>
		</div>
	</div>
</div>

app/views/portfolios/_technology_fields.html.erb
 <div class='nested-fields'>
	 <%= link_to_remove_association  f do %>
	    <i class="fa fa-times"></i>
	  <%end%>
    <div class="field">
      <%= f.text_field :name, placeholder: "Type name technology" %>
    </div>
    
   
  </div>

app/views/portfolios/angular.html.erb
<p id="notice"><%= notice %></p>
<p><%=link_to "Create New Item", new_portfolio_path %></p>
<% @angular_portfolio_items.each do |portfolio| %>
	<p><%=link_to portfolio.title, portfolio_show_path(portfolio) %></p>
	<p><%=portfolio.subtitle%></p>
	<p><%=portfolio.body%></p>
	<%= image_tag portfolio.thumb_image unless portfolio.main_image.nil?%>
	<%=link_to "Edit", edit_portfolio_path(portfolio) %>
	<%=link_to "delete", portfolio_path(portfolio), method: :delete, data: {confirm: "Are you sure?"} %>

	<hr>

<%end%>

app/views/portfolios/edit.html.erb
<div class="container">
	<p><%=link_to "Back", portfolios_path %></p>
	<h1>Edit Portfolio item</h1>
	<%= render "form", portfolio: @portfolio_item%>
</div>

app/views/portfolios/index.html.erb
<p><%=link_to "New Item", new_portfolio_path, class: "btn btn-primary my-2" if logged_in?(:site_admin)%></p>

<div class="album py-5 bg-light">
	<div class="container">
		<div class="row  <%= "sortable" if logged_in?(:site_admin)%>" >
			<%= render partial: 'portfolio_item', collection: @portfolio_items%>
		</div>
	</div>
</div>  
	

app/views/portfolios/new.html.erb
<div class="container portfolio-form">
	<p><%=link_to "Back", portfolios_path %></p>

<h1>Create a new Portfolio item</h1>

<%= render "form", portfolio: @portfolio_item%>


</div>

app/views/portfolios/ruby_on_rails.html.erb
<p id="notice"><%= notice %></p>
<p><%=link_to "Create New Item", new_portfolio_path %></p>
<% @rails_portfolio_items.each do |portfolio| %>
	<p><%=link_to portfolio.title, portfolio_show_path(portfolio) %></p>
	<p><%=portfolio.subtitle%></p>
	<p><%=portfolio.body%></p>
	<%= image_tag portfolio.thumb_image unless portfolio.main_image.nil?%>
	<%=link_to "Edit", edit_portfolio_path(portfolio) %>
	<%=link_to "delete", portfolio_path(portfolio), method: :delete, data: {confirm: "Are you sure?"} %>

	<hr>

<%end%>

app/views/portfolios/show.html.erb
<div class="container container-portfolio-item">
	<div class="row">
		<div class='col-md-7'> 
			<%= image_tag portfolio_img(@portfolio_item.main_image, 'main'), width: '100%'  %>

		</div>
		<div class='col-md-5'>
			
			
			<h1><%=@portfolio_item.title%></h1>
			<hr>
			<em><%=@portfolio_item.subtitle%></em>
			<p><%=@portfolio_item.body%></p>



			<h2>Technologies new</h2>

			<%unless @portfolio_item.technologies.nil?%>
				<% @portfolio_item.technologies.each do |t| %>
					<%=t.name%>
				<%end%>
			<%end%>
			<br>
			
		</div>

	</div>

</div>