config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:show, :index]

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/views/shared/_alerts.html.erb
 <% if  flash[:notice] %>
	<%=js add_gritter(flash[:notice], title: "Volodymyr", sticky: false) %>

<% elsif flash[:error]%>	
	<%=js add_gritter(flash[:notice], title: "Volodymyr", sticky: false) %>

<% else%>	
	<%=js add_gritter(flash[:alert], title: "Volodymyr", sticky: false) %>
 <%end%> 

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto app-footer">
    <div class="inner">
        <p><%=copyright_generator%></p>    
    </div>
</footer>
 

app/views/shared/_application_nav.html.erb
   <header class="masthead mb-auto">
        <div class="inner">
          <h3 class="masthead-brand">Cover</h3>
          <nav class="nav nav-masthead justify-content-center">
          	<%= nav_helper 'nav-link', 'div'%>
          	<%= login_helper 'nav-link' %> 
          </nav>
        </div>
</header>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
      <p><%=copyright_generator%>
      </p>
       <p>
        <a href="#">Back to top</a>
      </p>
</footer>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light blog-nav">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="container">
    <%= link_to "Vova", root_path, class: 'navbar-brand' %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <%= nav_helper 'nav-link', 'li' %>  
        <%= login_helper 'nav-link' %>  
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_blog_sidebar.html.erb
<aside class="col-md-4 blog-sidebar">
  <div class="p-3 mb-3 bg-light rounded">
    <h4 class="font-italic">About</h4>
    <p class="mb-0">Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
  </div>
  <div>
     <%= source_helper("alert alert-primary ") %>
  </div>
  <div class="sidebar-module p-3">
    
    <h4>Topics</h4>
    <%@side_bar_topics.each do |topic|%>
      <p><%= link_to topic.title, topic_path(topic)%></p>  
      

    <%end%>

  </div>


  <div class="p-3">
    <h4 class="font-italic">Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li> <a href="#"><%= fa_icon "github"%> </a> </li>
      <li><a href="#"><%= fa_icon "facebook"%> </a></li>
       <li><a href="#"><%= fa_icon "instagram"%></a></li>
      <li><a href="#"><%= fa_icon "twitter"%></a></li>
    </ol>
  </div>
</aside><!-- /.blog-sidebar -->

app/views/shared/_nav.html.erb
<%= link_to "Home", root_path, class: 'nav-link' %>
<%= link_to "About", about_path, class: 'nav-link'%>
<%= link_to "Contact", contact_path, class: 'nav-link'%>
<%= link_to "Blogs", blogs_path, class: 'nav-link' %>
<%= link_to "Portfolio", portfolios_path, class: 'nav-link' %>
<%= login_helper 'nav-link' %> 

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
	<div class="container">
		<p class="float-right">
			<%=link_to "View all portfolio items", portfolios_path %> |
			<a href="#">Back to top</a>
		</p>
		<p><%=copyright_generator%></p>

	</div>
</footer>

app/views/shared/_portfolio_header.html.erb
<section class="jumbotron text-center">
	<div class="container">
		<h1 class="jumbotron-heading">My portfolio</h1>
		<p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
	</div>
</section>

app/views/shared/_portfolio_nav.html.erb
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Explore</h4>
          <ul class="list-unstyled">
            <%= nav_helper 'nav-link', 'div'%>
            <%= login_helper 'nav-link' %> 

          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark box-shadow">
    <div class="container d-flex justify-content-between">
      <a href="#" class="navbar-brand d-flex align-items-center">
        
         Volodymyr Kostenko
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>